name: Publish Flutter app to Play Store
description: Publish the built Flutter app to the Google Play Store
inputs:
  android-service-account-json-base64:
    description: 'Base64 encoded Google Play service account JSON key'
    required: true
  android-package-name:
    description: 'The package name of the app to publish (e.g. com.example.myapp)'
    required: true
  android-track:
    description: 'The track to publish the app to (e.g. alpha, beta, production)'
    required: true
  android-release-files:
    description: 'The release files to publish to the Play Store (e.g. build/app/outputs/bundle/release/app-release.aab)'
    required: false
    default: 'build/app/outputs/bundle/release/app-release.aab'
runs:
  using: 'composite'
  steps:
    - name: Download service account key
      id: service_account
      uses: timheuer/base64-to-file@v1
      with:
        fileName: service-account.json
        encodedString: ${{ inputs.android-service-account-json-base64 }}

    - name: Publish to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ inputs.android-service-account-json-base64 }}
        packageName: ${{ inputs.android-package-name }}
        releaseFiles: ${{ inputs.android-release-files }}
        track: ${{ inputs.android-track }}
        serviceAccountJson: ${{ steps.service_account.outputs.filePath }}
