name: 'Flutter Analyze'
description: 'Runs Flutter analysis and formatting checks.'
inputs:
  treat-infos-as-fatal:
    description: 'Whether to treat info level issues as fatal.'
    required: false
    default: 'true'
  treat-warnings-as-fatal:
    description: 'Whether to treat warning level issues as fatal.'
    required: false
    default: 'true'
  no-pub:
    description: 'Whether to skip running pub get before analysis. Set to true if you have already run pub get in a previous step or if you are using a custom pub cache.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Run Analysis
      run: |
        flutter analyze . \
          ${{ inputs.treat-infos-as-fatal == 'false' && '--no-fatal-infos' || '' }} \
          ${{ inputs.treat-warnings-as-fatal == 'false' && '--no-fatal-warnings' || '' }} \
          ${{ inputs.no-pub == 'true' && '--no-pub' || '' }}
      shell: bash
