name: 'Flutter Analyze'
description: 'Runs Flutter analysis and formatting checks.'
inputs:
  analyze-fails-if-infos:
    description: 'Whether to treat info level issues as fatal.'
    required: false
    default: 'true'
  analyze-fails-if-warnings:
    description: 'Whether to treat warning level issues as fatal.'
    required: false
    default: 'true'
  no-pub:
    description: 'Whether to skip running pub get before analysis. Set to true if you have already run pub get in a previous step or if you are using a custom pub cache.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Run Analysis
      env:
        ANALYZE_FAILS_IF_INFOS: ${{ inputs.analyze-fails-if-infos }}
        ANALYZE_FAILS_IF_WARNINGS: ${{ inputs.analyze-fails-if-warnings }}
        NO_PUB: ${{ inputs.no-pub }}
      run: $GITHUB_ACTION_PATH/analyze.sh
      shell: bash
