name: Publish to Firebase App Distribution
description: Publish the app to Firebase App Distribution
inputs:
  firebase-service-account-base64:
    description: "Base64 encoded Firebase service account JSON key file"
    required: true
  app-id:
    description: "Firebase App ID (e.g. 1:1234567890:android:abcdef123456)"
    required: true
  groups:
    description: "Comma-separated list of tester groups to distribute the app to (optional)"
    required: false
  groups-file:
    description: "Path to a file containing a comma-separated list of tester groups to distribute the app to (optional)"
    required: false
  testers:
    description: "Comma-separated list of tester email addresses to distribute the app to (optional)"
    required: false
  testers-file:
    description: "Path to a file containing a comma-separated list of tester email addresses to distribute the app to (optional)"
    required: false
  release-notes:
    description: "Release notes for this distribution (optional)"
    required: false
  release-notes-file:
    description: "Path to a file containing release notes for this distribution (optional)"
    required: false
  debug:
    description: "Whether to enable debug logging for the upload process (default: false)"
    required: false
    default: "false" 
  test-devices:
    description: "Comma-separated list of test device IDs to distribute the app to (optional, only for iOS)"
    required: false
  test-devices-file:
    description: "Path to a file containing a comma-separated list of test device IDs to distribute the app to (optional, only for iOS)"
    required: false
  test-username:
    description: "Username for authenticating with the Firebase CLI (optional, only needed if not using a service account key)"
    required: false
  test-username-file:
    description: "Path to a file containing the username for authenticating with the Firebase CLI (optional, only needed if not using a service account key)"
    required: false
  test-password:
    description: "Password for authenticating with the Firebase CLI (optional, only needed if not using a service account key)"
    required: false
  test-password-file:
    description: "Path to a file containing the password for authenticating with the Firebase CLI (optional, only needed if not using a service account key)"
    required: false
  test-non-blocking:
    description: "Whether to run the upload process in non-blocking mode, which allows the workflow to continue without waiting for the upload to complete (default: false)"
    required: false
  test-case-ids:
    description: "Comma-separated list of test case IDs to associate with this distribution (optional)"
    required: false
  test-case-ids-file:
    description: "Path to a file containing a comma-separated list of test case IDs to associate with this distribution (optional)"
    required: false
runs:  
  using: "composite"
  steps:

    - name: Install Firebase CLI
      shell: bash
      run: |
        curl -sL https://firebase.tools | bash

    - name: Download Firebase service account key
      id: firebase_service_account
      uses: timheuer/base64-to-file@v1
      with:
        fileName: firebase-service-account.json
        encodedString: ${{ inputs.firebase-service-account-base64 }} 
    - name: Publish to Firebase App Distribution
      shell: bash
      run: |
        firebase appdistribution:distribute \
          --app ${{ inputs.app-id }} \
          ${ inputs.groups && "--groups " + inputs.groups } \
          ${ inputs.testers && "--testers " + inputs.testers } \
          ${ inputs.release-notes && "--release-notes " + inputs.release-notes } \
          ${ inputs.debug == "true" && "--debug" } \
          ${ inputs.test-devices && "--test-devices " + inputs.test-devices } \
          ${ inputs.test-username && "--test-username " + inputs.test-username } \
          ${ inputs.test-password && "--test-password " + inputs.test-password } \
          ${ inputs.test-non-blocking == "true" && "--non-blocking" } \
          ${ inputs.test-case-ids && "--test-case-ids " + inputs.test-case-ids } \
          ${ inputs.test-case-ids-file && "--test-case-ids-file " + inputs.test-case-ids-file } \
          --token "$(cat firebase-service-account.json | jq -r '.private_key')"