name: Publish to Firebase App Distribution
description: Publish the app to Firebase App Distribution
inputs:
  firebase-release-binary-file:
    description: 'File you want to upload'
    required: true
  firebase-service-account-base64:
    description: 'Base64 encoded Firebase service account JSON key file'
    required: true
  firebase-app-id:
    description: 'Firebase App ID (e.g. 1:1234567890:android:abcdef123456)'
    required: true
  firebase-groups:
    description: 'Comma-separated list of tester groups to distribute the app to (optional)'
    required: false
  firebase-groups-file:
    description: 'Path to a file containing a comma-separated list of tester groups to distribute the app to (optional)'
    required: false
  firebase-testers:
    description: 'Comma-separated list of tester email addresses to distribute the app to (optional)'
    required: false
  firebase-testers-file:
    description: 'Path to a file containing a comma-separated list of tester email addresses to distribute the app to (optional)'
    required: false
  firebase-release-notes:
    description: 'Release notes for this distribution (optional)'
    required: false
  firebase-release-notes-file:
    description: 'Path to a file containing release notes for this distribution (optional)'
    required: false
  firebase-debug:
    description: 'Whether to enable debug logging for the upload process (default: false)'
    required: false
    default: 'false'
  firebase-test-devices:
    description: 'Comma-separated list of test device IDs to distribute the app to (optional, only for iOS)'
    required: false
  firebase-test-devices-file:
    description: 'Path to a file containing a comma-separated list of test device IDs to distribute the app to (optional, only for iOS)'
    required: false
  firebase-test-username:
    description: 'Username for authenticating with the Firebase CLI (optional, only needed if not using a service account key)'
    required: false
  firebase-test-username-file:
    description: 'Path to a file containing the username for authenticating with the Firebase CLI (optional, only needed if not using a service account key)'
    required: false
  firebase-test-password:
    description: 'Password for authenticating with the Firebase CLI (optional, only needed if not using a service account key)'
    required: false
  firebase-test-password-file:
    description: 'Path to a file containing the password for authenticating with the Firebase CLI (optional, only needed if not using a service account key)'
    required: false
  firebase-test-non-blocking:
    description: 'Whether to run the upload process in non-blocking mode, which allows the workflow to continue without waiting for the upload to complete (default: false)'
    required: false
  firebase-test-case-ids:
    description: 'Comma-separated list of test case IDs to associate with this distribution (optional)'
    required: false
  firebase-test-case-ids-file:
    description: 'Path to a file containing a comma-separated list of test case IDs to associate with this distribution (optional)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install Firebase CLI
      shell: bash
      run: |
        npm install -g firebase-tools

    - name: Publish to Firebase App Distribution
      shell: bash
      env:
        FIREBASE_TOKEN: ${{ inputs.firebase-token }}
      run: |
        firebase appdistribution:diqstribute \
          --app ${{ inputs.firebase-app-id }} \
          ${ inputs.firebase-groups && "--groups " + inputs.firebase-groups } \
          ${ inputs.firebase-testers && "--testers " + inputs.firebase-testers } \
          ${ inputs.firebase-release-notes && "--release-notes " + inputs.firebase-release-notes } \
          ${ inputs.debug == "true" && "--debug" } \
          ${ inputs.firebase-test-devices && "--test-devices " + inputs.firebase-test-devices } \
          ${ inputs.firebase-test-username && "--test-username " + inputs.firebase-test-username } \
          ${ inputs.firebase-test-password && "--test-password " + inputs.firebase-test-password } \
          ${ inputs.firebase-test-non-blocking == "true" && "--non-blocking" } \
          ${ inputs.firebase-test-case-ids && "--test-case-ids " + inputs.firebase-test-case-ids } \
          ${ inputs.firebase-test-case-ids-file && "--test-case-ids-file " + inputs.firebase-test-case-ids-file } \
          ${{ inputs.firebase-release-binary-file }}
