name: Code Generation with Build Runner
description: 'Automatically discovers and runs code generation using build_runner for all Flutter packages in the repository.'

runs:
  using: 'composite'
  steps:
    - name: Add permissions
      run: chmod +x $GITHUB_ACTION_PATH/build_runner.sh
      shell: bash

    - name: Run Build Runner
      run: $GITHUB_ACTION_PATH/build_runner.sh
      shell: bash
