name: Code Generation with Build Runner
description: 'Automatically discovers and runs code generation using build_runner for all Flutter packages in the repository.'

runs:
  using: 'composite'
  steps:
    - name: Run Build Runner
      run: build_runner.sh
      shell: bash
