name: 'Flutter Actions Suite'
description: 'Builds a Flutter app for iOS, Android, Web, and Desktop, and deploys it.'
author: 'Spaccesi'
branding:
  icon: 'layers'
  color: 'blue'

inputs:
  flutter-version:
    description: 'The Flutter version to use.'
    required: true
  flutter-channel:
    description: 'The Flutter channel to use (stable, beta, dev, master).'
    required: false
    default: 'stable'
  github-token:
    description: 'GitHub token with permissions to deploy to GitHub Pages. Required if publish-coverage-report is set to true.'
    required: false
    default: ''
  deploy-coverage-report:
    description: 'Generate and deploy a HTML report optionally to GitHub Pages or as an artifact. Available options: none, github-pages, artifact. If set to github-pages, the report will be deployed to GitHub Pages using the provided GitHub token. If set to artifact, the report will be uploaded as an artifact of the workflow run. If set to none, no report will be generated or deployed.'
    required: false
    default: 'none'
  build-runner:
    description: 'Whether to run build_runner for code generation. This will run build_runner for all packages in the repository that have a build.yaml file.'
    required: false
    default: 'false'
  gen-l10n:
    description: 'Whether to run gen-l10n for code generation. This will run gen-l10n for all packages in the repository that have a l10n.yaml or l10n.yml file.'
    required: false
    default: 'false'
  gen-l10n-fails-if-untranslated:
    description: 'Whether to fail the gen-l10n step if untranslated strings are found. This will check for the presence of an untranslated-messages-file in the l10n configuration file and fail if the file is generated and contains untranslated strings.'
    required: false
    default: 'false'
  analyze-fails-if-infos:
    description: 'Whether to fail the analyze step if info level issues are found.'
    required: false
    default: 'false'
  analyze-fails-if-warnings:
    description: 'Whether to fail the analyze step if warning level issues are found.'
    required: false
    default: 'false'
  license:
    description: 'Whether to check for licenses of dependencies.'
    required: false
    default: 'false'
  compatible-licenses-conf-path:
    description: 'Path to a YAML file containing a list of compatible licenses. Required if license is set to true. The YAML file should have the following format: compatible_licenses: - MIT - BSD-3-Clause - Apache-2.0'
    required: false
    default: ''
  license-fails-on-warnings:
    description: 'Whether to fail the license check if any warnings are found.'
    required: false
    default: 'false'
  license-fails-on-info:
    description: 'Whether to fail the license check if any info level issues are found.'
    required: false
    default: 'false'
  test:
    description: 'Whether to run tests.'
    required: false
    default: 'false'
  analyze:
    description: 'Whether to run flutter analyze.'
    required: false
    default: 'false'
  coverage:
    description: 'Whether to run tests with coverage and generate a coverage report.'
    required: false
    default: 'false'
  build-platform:
    description: 'A comma separated list of platforms to build and deploy. Available options: android, ios, web, windows, macos, linux. If not set, all platforms will be built and deployed.'
    required: false
    default: ''
  publish-destination:
    description: 'Where to publish the built app. Available options: none, github-releases, store, . If set to github-releases, the app will be published to GitHub Releases using the provided GitHub token. If set to artifact, the app will be uploaded as an artifact of the workflow run. If set to none, the app will not be published.'
    required: false
    default: 'none'
 
runs:
  using: 'composite'
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: ${{ inputs.flutter-channel }}
        cache: true
    
    - name: Prepare Repository
      uses: Spaccesi/flutter-actions-suite/prepare@main
      with:
        build-runner: ${{ inputs.build-runner }}
        gen-l10n: ${{ inputs.gen-l10n }}
        gen-l10n-fails-if-untranslated: ${{ inputs.gen-l10n-fails-if-untranslated }}

    - name: Run Checks
      uses: Spaccesi/flutter-actions-suite/check@main
      with:
        analyze: ${{ inputs.analyze }}
        analyze-fails-if-infos: ${{ inputs.analyze-fails-if-infos }}
        analyze-fails-if-warnings: ${{ inputs.analyze-fails-if-warnings }}
        license: 'false'
        compatible-licenses-conf-path: ${{ inputs.compatible-licenses-conf-path }}
        license-fails-on-warnings: ${{ inputs.license-fails-on-warnings }}
        license-fails-on-info: ${{ inputs.license-fails-on-info }}
        test: ${{ inputs.test }}
        run-coverage: ${{ inputs.coverage }}
        deploy-report: ${{ inputs.deploy-coverage-report }}
        github-token: ${{ inputs.github-token }}

    - name: Build android
      if: contains(inputs.build-platform, 'android')
      uses: Spaccesi/flutter-actions-suite/build/ios@main
    
    - name: Build iOS
      if: contains(inputs.build-platform, 'ios')
      uses: Spaccesi/flutter-actions-suite/build/ios@main
      with:
        ios-signing-certificate-base64: ${{ secrets.IOS_SIGNING_KEY_BASE64 }}

    - name: Build web
      if: contains(inputs.build-platform, 'web')
      uses: Spaccesi/flutter-actions-suite/build/web@main 

    - name: Build windows
      if: contains(inputs.build-platform, 'windows')
      uses: Spaccesi/flutter-actions-suite/build/windows@main 

    - name: Build macos
      if: contains(inputs.build-platform, 'macos')
      uses: Spaccesi/flutter-actions-suite/build/macos@main 

    - name: Build linux
      if: contains(inputs.build-platform, 'linux')
      uses: Spaccesi/flutter-actions-suite/build/linux@main 

    - name: Publish to GitHub Releases
      if: inputs.publish-destination == 'github-releases'
      uses: Spaccesi/flutter-actions-suite/publish/github-releases@main

    - name: Publish to Firebase App Distribution
      if: inputs.publish-destination == 'app-distribution'
      uses: Spaccesi/flutter-actions-suite/publish/firebase-app-distribution@main 

    - name: Publish to Firebase Hosting
      if: inputs.publish-destination == 'hosting'
      uses: Spaccesi/flutter-actions-suite/publish/firebase-hosting@main  

    - name: Upload as Artifact
      if: inputs.publish-destination == 'artifact'
      uses: actions/upload-artifact@v3
     
    - name: Deploy to Play Store
      if: inputs.publish-destination == 'store' && contains(inputs.build-platform, 'android')
      uses: Spaccesi/flutter-actions-suite/publish/play-store@main

    - name: Deploy to ios App Store
      if: inputs.publish-destination == 'store' && contains(inputs.build-platform, 'ios')
      uses: Spaccesi/flutter-actions-suite/publish/app-store@main

    - name: Deploy to Microsoft Store
      if: inputs.publish-destination == 'store' && contains(inputs.build-platform, 'windows')
      uses: Spaccesi/flutter-actions-suite/publish/microsoft-store@main

    - name: Deploy to Mac App Store
      if: inputs.publish-destination == 'store' && contains(inputs.build-platform, 'macos')
      uses: Spaccesi/flutter-actions-suite/publish/mac-app-store@main 

    - name: Deploy to Linux App Store
      if: inputs.publish-destination == 'store' && contains(inputs.build-platform, 'linux')
      uses: Spaccesi/flutter-actions-suite/publish/snap-store@main
    


