name: 'Flutter Actions Suite'
description: 'Builds a Flutter app for iOS, Android, Web, and Desktop, and deploys it.'
author: 'Spaccesi'
branding:
  icon: 'layers'
  color: 'blue'

inputs:
  flutter-version:
    description: 'The Flutter version to use.'
    required: true
    default: 'latest'
  flutter-channel:
    description: 'The Flutter channel to use (stable, beta, dev, master).'
    required: false
    default: 'stable'
  flavor:
    description: 'The build flavor.'
    required: false
  dart-defines:
    description: 'Dart defines in KEY=VALUE format, one per line.'
    required: false
  build-name:
    description: 'The build name.'
    required: false
  build-number:
    description: 'The build number.'
    required: false
  github-token:
    description: 'GitHub token with permissions to deploy to GitHub Pages. Required if publish-coverage-report is set to true.'
    required: false
    default: ''
  deploy-coverage-report:
    description: 'Generate and deploy a HTML report optionally to GitHub Pages or as an artifact.'
    options:
      - 'none'
      - 'github-pages'
      - 'artifact'
    required: false
    default: 'none'
  deploy-android:
    description: 'Whether to build and deploy Android. Requires additional configuration for signing and publishing.'
    required: false
    options:
      - 'none'
      - 'store'
      - 'firebase'
    default: 'none'
  deploy-ios:
    description: 'Whether to build and deploy iOS. Requires additional configuration for signing and publishing
    required: false
    options:
      - 'none'
      - 'store'
      - 'firebase'
    default: 'none'
  deploy-web:
    description: 'Whether to build and deploy Web. Requires additional configuration for hosting and publishing.'
    required: false
    options:
      - 'none'
      - 'github-pages'
      - 'firebase'
    default: 'none'
  deploy-macos:
    description: 'Whether to build and deploy macOS. Requires additional configuration for signing and publishing.'
    required: false
    options:
      - 'none'
      - 'store'
    default: 'none'
  deploy-windows:
    description: 'Whether to build and deploy Windows. Requires additional configuration for signing and publishing.'
    required: false
    options:
      - 'none'
      - 'store'
    default: 'none'
  deploy-linux:
    description: 'Whether to build and deploy Linux. Requires additional configuration for signing and publishing.'
    required: false
    options:
      - 'none'
      - 'store'
    default: 'none'
  run-tests:
    description: 'Whether to run tests.'
    required: false
    default: true

runs:
  using: 'composite'
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: ${{ inputs.flutter-channel }}
        cache: true
# TODO