name: 'Flutter Actions Suite'
description: 'Builds a Flutter app for iOS, Android, Web, and Desktop, and deploys it.'
author: 'Spaccesi'
branding:
  icon: 'layers'
  color: 'blue'

inputs:
  flutter-version:
    description: 'The Flutter version to use.'
    required: true
  flutter-channel:
    description: 'The Flutter channel to use (stable, beta, dev, master).'
    required: false
    default: 'stable'
  github-token:
    description: 'GitHub token with permissions to deploy to GitHub Pages. Required if publish-coverage-report is set to true.'
    required: false
    default: ''
  deploy-coverage-report:
    description: 'Generate and deploy a HTML report optionally to GitHub Pages or as an artifact. Available options: none, github-pages, artifact. If set to github-pages, the report will be deployed to GitHub Pages using the provided GitHub token. If set to artifact, the report will be uploaded as an artifact of the workflow run. If set to none, no report will be generated or deployed.'
    required: false
    default: 'none'
 
runs:
  using: 'composite'
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: ${{ inputs.flutter-channel }}
        cache: true
    
    - name: Prepare Repository
      uses: Spaccesi/flutter-actions-suite/prepare@main
      with:
        build-runner: 'true'
        gen-l10n: 'true'
        gen-l10n-fails-if-untranslated: 'false'

    - name: Run Checks
      uses: Spaccesi/flutter-actions-suite/check@main
      with:
        analyze: 'true'
        analyze-fails-if-infos: 'false'
        analyze-fails-if-warnings: 'false'
        license: 'false'
        compatible-licenses-conf-path: ''
        license-fails-on-warnings: 'false'
        license-fails-on-info: 'false'
        test: 'true'
        run-coverage: 'true'
        deploy-report: ${{ inputs.deploy-coverage-report }}
        github-token: ${{ inputs.github-token }}
