name: Check license
description: Check that all dependencies licenses are compatible with the project. https://pub.dev/packages/license_checker is used to check the licenses of the dependencies. The action can be configured to fail if incompatible licenses are found or to just print a warning. A file containing a list of compatible licenses can also be provided.
inputs:
  compatible-licenses-conf-path:
    description: 'Path to a file containing a list of compatible licenses.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install package to check licenses
      run: dart pub global activate license_checker
      shell: bash

    - name: Check licenses
      shell: bash
      run: |
        # Run license check and capture output
        OUTPUT=$(lic_ck check-licenses -c ${{ inputs.compatible-licenses-conf-path }} -i -a)
        
        # Check if output doesnt contains "No package licenses need approval!"
        if ! echo "$OUTPUT" | grep -q "No package licenses need approval!"; then
          echo "::error::Found incompatible licenses."
          echo "$OUTPUT"
          exit 1
        fi

        echo "All licenses are compatible."