name: Take information from the changelog and create a release note
description: |
  This action takes the information from the changelog and creates a release note. It can
  also create a release on GitHub and upload the release note as an artifact.
inputs:
  changelog-path:
    description: 'The path to the changelog file. This should be a relative path from the root of the repository.'
    required: false
    default: 'CHANGELOG.md'
  fails-on-missing-changelog:
    description: 'Whether the action should fail if the changelog file is missing.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Create release note from changelog
      id: create_release_note
      shell: bash
      run: |
        if [ ! -f "${{ inputs.changelog-path }}" ]; then
          echo "🚨 Changelog file not found at path: ${{ inputs.changelog-path }}"
          if [[ "${{ inputs.fails-on-missing-changelog }}" == "true" ]]; then
            exit 1
          fi
        fi

        # Extract the latest release note from the changelog
        RELEASE_NOTE=$(awk '/^# /{flag=1; next} /^# /{flag=0} flag' "${{ inputs.changelog-path }}" | sed '$d')
        if [ -z "$RELEASE_NOTE" ]; then
          echo "🚨 No release note found in the changelog."
          if [[ "${{ inputs.fails-on-missing-changelog }}" == "true" ]]; then
            exit 1
          fi
        fi

        echo "Release note extracted from changelog:"
        echo "$RELEASE_NOTE"

        # Set the release note as an output variable
        echo "::set-output name=release_note::$RELEASE_NOTE"
