name: Take information from the changelog and create a release note
description: |
  This action takes the information from the changelog and creates a release note. It can
  also create a release on GitHub and upload the release note as an artifact.
inputs:
  changelog-path:
    description: 'The path to the changelog file. This should be a relative path from the root of the repository.'
    required: false
    default: 'CHANGELOG.md'
  fails-on-missing-changelog:
    description: 'Whether the action should fail if the changelog file is missing.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Create release note from changelog
      id: create_release_note
      shell: bash
      env:
        CHANGELOG_PATH: ${{ inputs.changelog-path }}
        FAILS_ON_MISSING_CHANGELOG: ${{ inputs.fails-on-missing-changelog }}
      run: release-note-from-changelog.sh
        
