name: Publish to Firebase Hosting
description: Publish the built web app to Firebase Hosting
inputs:
  firebase-service-account-base64:
    description: 'Base64 encoded Firebase service account key (JSON file)'
    required: true
  firebase-project-id:
    description: 'Firebase project ID to publish to'
    required: false
  firebase-target:
    description: 'Firebase Hosting target to deploy to (optional)'
    required: false
  firebase-debug:
    description: 'Whether to enable debug logging for the deployment process (default: false)'
    required: false
    default: 'false'
  firebase-message:
    description: 'A message to include with the deployment (optional)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install Firebase CLI
      shell: bash
      run: npm install -g firebase-tools

    - name: Prepare Google Application Credentials
      shell: bash
      run: |
        echo "${{ inputs.firebase-service-account-base64 }}" | base64 --decode > "google-application-credentials.json"

    - name: Publish to Firebase Hosting
      shell: bash
      env:
        GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
      run: |
        firebase deploy \
          --only hosting${{ inputs.firebase-target != '' && format(':{0}', inputs.firebase-target) || '' }} \
          ${{ inputs.firebase-project-id != '' && format('--project {0}', inputs.firebase-project-id) || '' }} \
          ${{ inputs.firebase-debug == 'true' && '--debug' || '' }} \
          ${{ inputs.firebase-message != '' && format('--message {0}', inputs.firebase-message) || '' }}

    - name: Remove credentials file
      if: success() || failure()
      shell: bash
      run: |
        rm google-application-credentials.json
