name: Publish to Firebase Hosting
description: Publish the built web app to Firebase Hosting
inputs:
  firebase-service-account-base64:
    description: "Base64 encoded Firebase service account key (JSON file)"
    required: true
  project-id:
    description: "Firebase project ID to publish to"
    required: true
  target:
    description: "Firebase Hosting target to deploy to (optional, defaults to 'default')"
    required: false
  public-dir:
    description: "Directory containing the built web app to publish (optional, defaults to 'build/web')"
    required: false
  debug:
    description: "Whether to enable debug logging for the deployment process (default: false)"
    required: false
    default: "false"
  message:
    description: "A message to include with the deployment (optional)"
    required: false
runs:  
  using: "composite"
  steps:
    - name: Install Firebase CLI
      shell: bash
      run: npm install -g firebase-tools

    - name: Publish to Firebase Hosting
      shell: bash
      env:
        FIREBASE_TOKEN: ${{ inputs.firebase-token }}
      run: |
        firebase deploy \
          --only hosting:${{ inputs.target || 'default' }} \
          --project ${{ inputs.project-id }} \
          --public ${{ inputs.public-dir || 'build/web' }} \
          ${ inputs.debug == "true" && "--debug" }
          ${ inputs.message && "--message " + inputs.message }