name: 'Flutter Analyze'
description: 'Runs Flutter analysis and formatting checks.'
inputs:
  treat-infos-as-fatal:
    description: 'Whether to treat info level issues as fatal.'
    required: false
    default: true
  treat-warnings-as-fatal:
    description: 'Whether to treat warning level issues as fatal.'
    required: false
    default: true

runs:
  using: 'composite'
  steps:
    - name: Run Analysis
      run: |
        flutter analyze . \
          ${{ inputs.treat-infos-as-fatal == 'false' && '--no-fatal-infos' || '' }} \
          ${{ inputs.treat-warnings-as-fatal == 'false' && '--no-fatal-warnings' || '' }} \
          --no-pub
      shell: bash
