name: Publish macOS App Store
description: Publish the macOS app to the App Store using Flutter
inputs:
  apple-api-key-id:
    description: 'Apple API key ID (e.g. developer@apple.com)'
    required: true
  apple-api-key-issuer-id:
    description: 'Apple API issuer ID (UUID format)'
    required: true
  apple-api-key-content:
    description: 'Base64 encoded content of the Apple API private key (.p8 file)'
    required: true
  macos-provisioning-profile-base64:
    description: 'Base64 encoded content of the macOS provisioning profile (.provisionprofile file)'
    required: true
  macos-app-path:
    description: 'Path to the macOS app'
    required: false
    default: 'build/macos/pkg/*.pkg'

runs:
  using: 'composite'
  steps:
    - name: Install Provisioning Profile
      shell: bash
      env:
        PROVISIONING_PROFILE_BASE64: ${{ inputs.macos-provisioning-profile-base64 }}
      run: |
        # create variables
        PP_PATH=$RUNNER_TEMP/build_pp.provisionprofile

        # import provisioning profile from secrets
        echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode -o $PP_PATH

        # apply provisioning profile
        mkdir -p ~/Library/ProvisioningProfiles
        cp $PP_PATH ~/Library/ProvisioningProfiles

        # Extract UUID and copy with UUID name to ensure detection
        UUID=`/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< $(security cms -D -i $PP_PATH)`
        cp $PP_PATH ~/Library/ProvisioningProfiles/$UUID.provisionprofile

        echo "PP_PATH=$PP_PATH" >> $GITHUB_ENV
        echo "profile_uuid=$UUID" >> $GITHUB_ENV

    - name: Upload app to App Store Connect
      shell: bash
      env:
        API_KEY_ID: ${{ inputs.apple-api-key-id }}
        API_ISSUER_ID: ${{ inputs.apple-api-key-issuer-id }}
        API_KEY_CONTENT: ${{ inputs.apple-api-key-content }}
        MACOS_APP_PATH: ${{ inputs.macos-app-path }}
      run: |
        # Create private key file
        mkdir -p ~/.appstoreconnect/private_keys
        echo "$API_KEY_CONTENT" > ~/.appstoreconnect/private_keys/AuthKey_$API_KEY_ID.p8

        # Upload
        # Note: altool uses --type osx for macOS apps
        xcrun altool --upload-app --type osx --file "$MACOS_APP_PATH" --apiKey "$API_KEY_ID" --apiIssuer "$API_ISSUER_ID"
