name: Build docs using Dartdoc
description: |
  Build documentation for the Flutter project using Dartdoc

inputs:
  output-directory:
    description: 'Directory to output the generated documentation (default: docs)'
    required: false
    default: 'docs'
  validate-links:
    description: 'Whether to validate links in the generated documentation. This can help catch broken links but may increase build time.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Build Documentation
      shell: bash
      run: |
        dartdoc \
          --output ${ { inputs.output-directory } } \
          ${{ inputs.validate-links == 'true' && '--validate-links' || '' }}
